//
// GuestAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire



open class GuestAPI {
    /**
     Guest Settings
     
     - parameter accept: (header) &#x60;application/json&#x60; 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func guestGetGuestSettings(accept: String, completion: @escaping ((_ data: SuccessResponse?,_ error: Error?) -> Void)) {
        guestGetGuestSettingsWithRequestBuilder(accept: accept).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     Guest Settings
     - GET /guests
     - Guest settings and parameters
     - API Key:
       - type: apiKey x-api-key 
       - name: apiKey
     - examples: [{contentType=application/json, example={"empty": false}}]
     
     - parameter accept: (header) &#x60;application/json&#x60; 

     - returns: RequestBuilder<SuccessResponse> 
     */
    open class func guestGetGuestSettingsWithRequestBuilder(accept: String) -> RequestBuilder<SuccessResponse> {
        let path = "/guests"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        
        let url = URLComponents(string: URLString)
        let nillableHeaders: [String: Any?] = [
            "Accept": accept
        ]
        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<SuccessResponse>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false, headers: headerParameters)
    }

}
