//
// SportTitleAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire



open class SportTitleAPI {
    /**
     Get All Sport Titles
     
     - parameter accept: (header) Set to &#x60;application/json&#x60; 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func sportTitleGetGetAllSportTitles(accept: String, completion: @escaping ((_ data: SportTitleGetAllSportTitlesResponse?,_ error: Error?) -> Void)) {
        sportTitleGetGetAllSportTitlesWithRequestBuilder(accept: accept).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     Get All Sport Titles
     - GET /sports
     - 
     - API Key:
       - type: apiKey x-access-token 
       - name: accessToken
     - API Key:
       - type: apiKey x-api-key 
       - name: apiKey
     - examples: [{contentType=application/json, example={"empty": false}}]
     
     - parameter accept: (header) Set to &#x60;application/json&#x60; 

     - returns: RequestBuilder<SportTitleGetAllSportTitlesResponse> 
     */
    open class func sportTitleGetGetAllSportTitlesWithRequestBuilder(accept: String) -> RequestBuilder<SportTitleGetAllSportTitlesResponse> {
        let path = "/sports"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        
        let url = URLComponents(string: URLString)
        let nillableHeaders: [String: Any?] = [
            "Accept": accept
        ]
        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<SportTitleGetAllSportTitlesResponse>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false, headers: headerParameters)
    }

}
