//
// BookingsAddNewBookingResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct BookingsAddNewBookingResponse: Codable {

    public var message: String?
    public var result: Bool?
    public var payload: Booking?

    public init(message: String?, result: Bool?, payload: Booking?) {
        self.message = message
        self.result = result
        self.payload = payload
    }


}

