//
// Booking.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Booking: Codable,Identifiable {

    public var id = UUID()
    public var _id: Int?
    public var userId: String?
    public var trainerId: String?
    public var date: String?
    public var serviceId: String?
    public var is_paid: String?
    public var time: String?
    public var petProfileId: String?
    public var status: String?
    public var createdAt: String?
    public var updatedAt: String?
    public var trainer: Trainer?
    public var users: User?
    public var petProfile: PetProfile?

    public init(_id: Int?, userId: String?, trainerId: String?, date: String?, serviceId: String?,is_paid: String?, time: String?, petProfileId: String?, status: String?, createdAt: String?, updatedAt: String?, trainer: Trainer?, users: User?, petProfile: PetProfile?) {
        self._id = _id
        self.userId = userId
        self.trainerId = trainerId
        self.date = date
        self.serviceId = serviceId
        self.time = time
        self.petProfileId = petProfileId
        self.status = status
        self.createdAt = createdAt
        self.updatedAt = updatedAt
        self.trainer = trainer
        self.users = users
        self.petProfile = petProfile
        self.is_paid = is_paid
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case userId = "user_id"
        case trainerId = "trainer_id"
        case date
        case serviceId = "service_id"
        case time
        case petProfileId = "pet_profile_id"
        case status
        case createdAt = "created_at"
        case updatedAt = "updated_at"
        case trainer
        case users
        case petProfile
        case is_paid = "is_paid"
    }


}

