//
// Experience.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Experience: Codable,Identifiable,Hashable {

    public var id: UUID?
    public var _id: Int?
    public var experience: String?
    public var createdAt: String?
    public var updatedAt: String?

    public init(_id: Int?, experience: String?, createdAt: String?, updatedAt: String?) {
        self._id = _id
        self.experience = experience
        self.createdAt = createdAt
        self.updatedAt = updatedAt
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case experience
        case createdAt = "created_at"
        case updatedAt = "updated_at"
    }


}

