//
// File.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import UIKit



public struct File: Codable,Hashable,Identifiable {
   
    
    public let id = UUID()
    public var _id:Int?
    public var uuid: String?
    public var key: String?
    public var originalFilename: String?
    public var publicUrl: String?
    public var permalink: String?
    public var attachableId: Int?
    public var fileUrl: String?
    public var index :Int?
    public var fileImage = UIImage(systemName: "person.fill")
    public var category: String?

    public init(uuid: String?, key: String?, originalFilename: String?, publicUrl: String?, permalink: String?, attachableId: Int?, fileUrl: String?,fileImage:UIImage, category: String?,_id:Int) {
        self.uuid = uuid
        self.key = key
        self.originalFilename = originalFilename
        self.publicUrl = publicUrl
        self.permalink = permalink
        self.attachableId = attachableId
        self.fileUrl = fileUrl
        self.fileImage = fileImage
        self.category = category
        self._id = _id
    }

    public enum CodingKeys: String, CodingKey { 
        case uuid
        case key
        case originalFilename = "original_filename"
        case publicUrl = "public_url"
        case permalink
        case attachableId = "attachable_id"
        case fileUrl = "file_url"
        case category
        case _id = "id"
    }


}

