//
// Paginator.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Paginator: Codable {

    public var currentPage: Double?
    public var perPage: Double?
    public var from: Double?
    public var to: Double?
    public var total: Double?
    public var lastPage: Double?

    public init(currentPage: Double?, perPage: Double?, from: Double?, to: Double?, total: Double?, lastPage: Double?) {
        self.currentPage = currentPage
        self.perPage = perPage
        self.from = from
        self.to = to
        self.total = total
        self.lastPage = lastPage
    }

    public enum CodingKeys: String, CodingKey { 
        case currentPage = "current_page"
        case perPage = "per_page"
        case from
        case to
        case total
        case lastPage = "last_page"
    }


}

