//
// Service.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Service: Codable,Identifiable,Hashable {

    public let id = UUID()
    public var _id: Int?
    public var service: String?
    public var createdAt: String?
    public var updatedAt: String?
    public var isShow = false
    var priceNew = ""
    public var pivot:Pivot?

    public init(_id: Int?, service: String?, createdAt: String?, updatedAt: String?,pivot:Pivot?) {
        self._id = _id
        self.service = service
        self.createdAt = createdAt
        self.updatedAt = updatedAt
        self.pivot?.price = pivot?.price
        self.pivot?.service_id = pivot?.service_id
        self.pivot?.trainer_id = pivot?.trainer_id
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case service
        case createdAt = "created_at"
        case updatedAt = "updated_at"
        case pivot = "pivot"
    }


}

public struct Pivot: Codable,Identifiable,Hashable {

    public let id = UUID()
    public var service_id: Int?
    public var trainer_id: Int?
    public var price: String?
    var priceNew = ""
  

    public init(service_id: Int?,trainer_id: Int?, price: String?) {
        self.service_id = service_id
        self.trainer_id = trainer_id
        self.price = price
    }

    public enum CodingKeys: String, CodingKey {
        case service_id = "service_id"
        case price = "price"
        case trainer_id = "trainer_id"
    }


}

