//
// SportTitle.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct SportTitle: Codable,Identifiable,Hashable {
    public let id = UUID()
    public var _id: Int?
    public var title: String?
    public var createdAt: String?
    public var updatedAt: String?
    public var isShow = false
    

    public init(_id: Int?, title: String?, createdAt: String?, updatedAt: String?) {
        self._id = _id
        self.title = title
        self.createdAt = createdAt
        self.updatedAt = updatedAt
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case title
        case createdAt = "created_at"
        case updatedAt = "updated_at"
    }


}

