//
// Trainer.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Trainer:  Codable,Identifiable {
    
    


    public let id = UUID()
    public var _id: Int?
    public var userId: Int?
    public var businessName: String?
    public var location: String?
    public var latitude: String?
    public var longitude: String?
    public var phone: String?
    public var website: String?
    public var createdAt: String?
    public var updatedAt: String?
    public var trainingPlace: String?
    public var experienceId: Int?
    public var users: User?
    public var services: [Service]?
    public var experience: Experience?
    public var sportTitles: [SportTitle]?
    public var file: [File]?
    public var photos: [File]?
    public var certificate: [File]?

    public init(_id: Int?, userId: Int?, businessName: String?, location: String?, latitude: String?, longitude: String?, phone: String?, website: String?, createdAt: String?, updatedAt: String?, trainingPlace: String?, experienceId: Int?, users: User?, services: [Service]?, experience: Experience?, sportTitles: [SportTitle]?, file: [File]?, photos: [File]?, certificate: [File]?) {
        self._id = _id
        self.userId = userId
        self.businessName = businessName
        self.location = location
        self.latitude = latitude
        self.longitude = longitude
        self.phone = phone
        self.website = website
        self.createdAt = createdAt
        self.updatedAt = updatedAt
        self.trainingPlace = trainingPlace
        self.experienceId = experienceId
        self.users = users
        self.services = services
        self.experience = experience
        self.sportTitles = sportTitles
        self.file = file
        self.photos = photos
        self.certificate = certificate
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case userId = "user_id"
        case businessName = "business_name"
        case location
        case latitude
        case longitude
        case phone
        case website
        case createdAt = "created_at"
        case updatedAt = "updated_at"
        case trainingPlace = "training_place"
        case experienceId = "experience_id"
        case users
        case services
        case experience
        case sportTitles = "sport_titles"
        case file
        case photos
        case certificate
    }


}

