//
// Treatment.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Treatment: Codable {

    public var _id: Int?
    public var petProfileId: String?
    public var treatment: String?
    public var createdAt: String?
    public var updatedAt: String?

    public init(_id: Int?, petProfileId: String?, treatment: String?, createdAt: String?, updatedAt: String?) {
        self._id = _id
        self.petProfileId = petProfileId
        self.treatment = treatment
        self.createdAt = createdAt
        self.updatedAt = updatedAt
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case petProfileId = "pet_profile_id"
        case treatment
        case createdAt = "created_at"
        case updatedAt = "updated_at"
    }


}

