//
// User.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct User: Codable {

    public var _id: String?
    public var uuid: String?
    public var name: String?
    public var email: String?
    public var phone: String?
    public var age: String?
    public var location: String?
    public var latitude: String?
    public var longitude: String?
    public var avatarUrl: String?
    public var timezone: String?
    public var trainer: String?
    public var accessToken: String?
    public var userRole : String?
    public var countryCode = ""
    public var businessCountryCode = ""

    public init(_id: String?, uuid: String?, name: String?, email: String?, phone: String?, age: String?, location: String?, latitude: String?, longitude: String?, avatarUrl: String?, timezone: String?, trainer: String?, accessToken: String?,userRole:String?) {
        self._id = _id
        self.uuid = uuid
        self.name = name
        self.email = email
        self.phone = phone
        self.age = age
        self.location = location
        self.latitude = latitude
        self.longitude = longitude
        self.avatarUrl = avatarUrl
        self.timezone = timezone
        self.trainer = trainer
        self.accessToken = accessToken
        self.userRole = userRole
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case uuid
        case name
        case email
        case phone
        case age
        case location
        case latitude
        case longitude
        case avatarUrl = "avatar_url"
        case timezone
        case trainer
        case accessToken = "access_token"
        case userRole = "user_role"
    }


}

